### ISSUE TITLE
Compatibility with Fitbit sense

### ISSUE THREAD

**Issue by tom-hooper** [AdamFoster/FitbitLifx#2]
Needs update to work on Fitbit sense

**Comment by keenun** [comment]
Ditto. Would love to see this on the Sense.

**Comment by AdamFoster** [comment]
Submitted a new version with Sense and Versa3 compatibility to Fitbit - currently pending their approval.
Note: I no longer own a Fitbit, so future updates are unlikely. Happy to help with any questions on the code if anyone wants to build it themselves.

**Comment by AdamFoster** [comment]
New version approved by Fitbit with Sense and Versa 3 compatibility.
